version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Barlog951"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Barlog951"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"