# .github/settings.yml
repository:
  name: SeedShield
  description: Secure BIP39 seed phrase viewer
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "test"
          - "security-scan"
          - "dependency-review"
      enforce_admins: false
      restrictions:
        users: ["Barlog951"]
        teams: []